#!/usr/bin/env python3
"""
Generator for Subject 021: AGK - Airframe, Systems, Electrics & Powerplant
Volume 1: Chapters 04 to 06
- Chapter 04: Flight Control Systems (Primary, Secondary & Powered Controls)
- Chapter 05: Pneumatic Systems & Air Conditioning (Bleed Air & Packs)
- Chapter 06: Pressurisation Systems (Outflow Valves & Regimes)

Fully aligned with CAE Oxford Book 2 (Airframes and Systems) and EASA ECQB / AviationExam.
"""

import os
import sys
from pdf_builder import PDFBuilder

OUTPUT_DIR = "resumenes/convocatoria_2/021_agk_airframe_systems_powerplant"

def build_agk_ch04():
    pdf_path = os.path.join(OUTPUT_DIR, "021_ch04_flight_controls.pdf")
    pdf = PDFBuilder("Airframe & Systems", "021", "Chapter 4: Flight Control Systems")

    # Cover / Header Banner
    pdf.add_title_banner(
        "Airframe & Systems",
        4,
        "Flight Control Systems (Primary, Secondary & Powered)",
        "149-198"
    )

    pdf.add_heading_1("1. Primary vs Secondary Flight Controls & Axes of Motion")
    pdf.add_paragraph(
        "Aircraft maneuvering is governed by aerodynamic control surfaces positioned along the three orthogonal axes intersecting at the Center of Gravity (CG):"
    )

    axes_data = [
        ["Ailerons (and Roll Spoilers)", "Longitudinal Axis (Nose to Tail)", "ROLL (Lateral control) via control wheel rotation or sidestick lateral deflection."],
        ["Elevator (or Variable Tailplane / Stabilator)", "Lateral Axis (Wingtip to Wingtip)", "PITCH (Longitudinal control) via control column push/pull or sidestick longitudinal deflection."],
        ["Rudder", "Normal / Vertical Axis (Through CG)", "YAW (Directional control) via left/right rudder pedal deflection."]
    ]
    pdf.add_table(["Control Surface", "Aircraft Axis of Motion", "Type of Motion & Cockpit Input"], axes_data, col_widths=[140.0, 150.0, 210.0])

    pdf.add_heading_1("2. Manual vs Reversible vs Irreversible Power-Assisted Controls")
    pdf.add_paragraph(
        "As aircraft airspeed and mass increase, aerodynamic hinge moments exceed human muscular capability, requiring powered actuation:"
    )
    pdf.add_bullet("Manual / Reversible Controls", "Aerodynamic hinge forces acting on control surfaces are transmitted directly back through cables and push-pull rods to the cockpit controls. The pilot directly 'feels' aerodynamic resistance.")
    pdf.add_bullet("Fully Powered / Irreversible Controls (PFCUs)", "Hydraulic actuators (Power Flight Control Units) drive the control surfaces. Aerodynamic airloads are absorbed entirely by the hydraulic actuators and airframe structure. ZERO aerodynamic feedback reaches the pilot's controls!")
    pdf.add_bullet("Artificial Feel Units (Q-Feel)", "Because irreversible controls lack natural tactile feedback, artificial feel units must be installed. A dynamic pressure capsule ('Q-pot') fed by pitot and static pressure increases control centering spring resistance proportionally to dynamic pressure (q = 1/2 rho V^2). As airspeed increases, controls stiffen, preventing structural over-stressing!")

    pdf.add_callout(
        "trap",
        "Artificial Feel Unit (Q-Feel) Characteristics",
        "- At low airspeeds (take-off/landing): Control resistance is light, allowing full control deflection.\n"
        "- At high airspeeds (cruise/dive): Control resistance is very stiff. The pilot cannot easily over-deflect controls and exceed airframe limit load factor (+2.5g)!\n"
        "- If the Q-feel pitot line becomes blocked by ice in cruise, control feel remains erroneously stiff during subsequent descent and approach!",
        max_chars=86
    )

    pdf.add_heading_1("3. Aerodynamic Balance & Control Tabs")
    tab_data = [
        ["Inset Hinge / Horn Balance", "Surface area placed ahead of the hinge line.", "Aerodynamic airloads ahead of the hinge help rotate the surface, reducing pilot control effort."],
        ["Trim Tab", "Small auxiliary surface hinged at trailing edge of primary control.", "Deflects opposite to desired surface deflection, generating aerodynamic force that holds the primary control in position, trimming control forces to ZERO."],
        ["Balance Tab", "Mechanically linked to move OPPOSITE to the primary control surface.", "Reduces pilot control stick forces by providing an assisting aerodynamic moment."],
        ["Anti-Balance Tab", "Mechanically linked to move in the SAME DIRECTION as primary surface.", "Increases control stick forces. Mandatory on all-moving tailplanes (stabilators) to prevent pilot over-controlling and structural damage."],
        ["Servo Tab", "Directly linked to cockpit controls; primary surface is completely free-floating.", "Pilot moves the servo tab; aerodynamic lift generated by the tab drives the main control surface in the opposite direction. Used on large vintage aircraft (e.g. Britannia)."],
        ["Spring Tab", "Incorporates a torsion spring in the control linkage.", "Acts as a rigid connection at low speeds (manual control), but spring compresses at high speeds, converting the tab into an assisting servo tab under heavy aerodynamic loads."]
    ]
    pdf.add_table(["Tab / Device Type", "Operating Principle", "Operational Function & Purpose"], tab_data, col_widths=[125.0, 175.0, 200.0])

    pdf.add_heading_1("4. Secondary Controls: Spoilers, Airbrakes & High-Lift Systems")
    pdf.add_paragraph(
        "Spoilers are rectangular hinged panels mounted on the upper surface of the wing. They perform three distinct functions:"
    )
    pdf.add_bullet("Roll Spoilers (Flight Spoilers)", "Deflect asymmetrically on the down-going wing only during roll commands, assisting ailerons and eliminating adverse yaw.")
    pdf.add_bullet("Speedbrakes (In-Flight Deceleration)", "Deflect symmetrically on both wings in flight. Increases parasite drag and reduces lift, steepening descent path without increasing airspeed.")
    pdf.add_bullet("Ground Spoilers (Lift Dumpers)", "Deploy to maximum deflection (up to 50-60°) automatically upon main wheel touchdown or rejected take-off (RTO). Dumps virtually all wing lift instantly, transferring aircraft weight fully onto the landing gear wheels for maximum anti-skid tyre braking traction, while adding massive aerodynamic drag.")

    pdf.add_heading_1("5. AviationExam Practice Questions (with Explanations)")
    questions_ch04 = [
        ("Q1: In an aircraft equipped with irreversible hydraulic powered flight controls, how does the pilot receive tactile aerodynamic force feedback?",
         "[A] Through direct mechanical cable feedback from the elevators\n[B] Through an artificial feel unit (Q-feel) that increases control resistance proportionally to dynamic pressure (1/2 rho V^2)\n[C] By engine thrust levers vibrating\n[D] Through aerodynamic tabs on the rudder",
         "CORRECT: [B]. Irreversible PFCUs isolate the control column from aerodynamic hinge loads. An artificial feel unit (Q-pot) uses pitot/static dynamic pressure to stiffen controls as airspeed increases."),
        ("Q2: What is the primary operational purpose of an anti-balance tab fitted to an all-flying tailplane (stabilator)?",
         "[A] To reduce pilot control stick forces\n[B] To increase stick forces and prevent the pilot from over-controlling the sensitive stabilator\n[C] To trim the aircraft for zero pitch force\n[D] To improve low-speed lift",
         "CORRECT: [B]. All-moving tailplanes have very low hinge moments. An anti-balance tab moves in the SAME direction as the stabilator, generating resistance that increases pilot stick force to provide tactile feel and prevent structural damage."),
        ("Q3: What is the primary operational effect of ground spoiler (lift dumper) deployment upon touchdown?",
         "[A] Decreasing wheel brake temperature\n[B] Destroying wing lift instantly to transfer aircraft weight onto wheels, dramatically improving wheel braking friction\n[C] Pitching the nose down onto the runway\n[D] Cooling the engine reverse thrust ducts",
         "CORRECT: [B]. Ground spoilers destroy wing lift immediately upon touchdown, shifting full aircraft weight onto tyres so multi-disc brakes achieve maximum anti-skid friction efficiency."),
        ("Q4: Which direction does a conventional pitch trim tab deflect relative to the elevator when trimming for nose-up pitch?",
         "[A] In the same direction (upwards)\n[B] In the opposite direction (downwards)\n[C] It remains neutral\n[D] It oscillates continuously",
         "CORRECT: [B]. To hold the elevator deflected UPWARDS (nose-up pitch), the trim tab at the trailing edge deflects DOWNWARDS. The upward aerodynamic force on the tab holds the elevator up without pilot force.")
    ]

    for q_text, opts, exp in questions_ch04:
        pdf.add_heading_2(q_text)
        pdf.add_paragraph(opts, max_chars=88)
        pdf.add_callout("definition", "Detailed Answer Explanation", exp, max_chars=86)

    pdf.compile_pdf(pdf_path)
    print(f"AGK Chapter 4 compiled: {pdf_path}")


def build_agk_ch05():
    pdf_path = os.path.join(OUTPUT_DIR, "021_ch05_pneumatics_air_conditioning.pdf")
    pdf = PDFBuilder("Airframe & Systems", "021", "Chapter 5: Pneumatics & Air Conditioning")

    # Cover / Header Banner
    pdf.add_title_banner(
        "Airframe & Systems",
        5,
        "Pneumatic Systems & Air Conditioning (Packs)",
        "199-216"
    )

    pdf.add_heading_1("1. Engine Bleed Air Sources & Precoolers")
    pdf.add_paragraph(
        "Pressurized hot air is extracted from the compressor stages of gas turbine engines to power pneumatic systems, "
        "cabin air conditioning, wing thermal anti-icing, and engine starting:"
    )
    pdf.add_bullet("Bleed Ports", "Intermediate Pressure (IP) stage used during high thrust (take-off, climb, cruise); High Pressure (HP) stage tapped automatically at low thrust (descent, idle) via an HP bleed valve when IP pressure is insufficient.")
    pdf.add_bullet("Bleed Parameters", "Raw bleed air leaves the compressor at high temperature (up to 400°C) and pressure (up to 200 psi).")
    pdf.add_bullet("Precooler", "An air-to-air heat exchanger located in the engine pylon. Uses cool engine fan bypass air to reduce bleed air temperature down to ~200°C before entering the main pneumatic manifold.")
    pdf.add_bullet("Manifold Isolation", "A crossbleed valve allows one engine to supply both sides of the aircraft pneumatic manifold, or isolates left/right systems during pneumatic leak detection.")

    pdf.add_heading_1("2. The Air Cycle Machine (ACM) & Air Conditioning Pack")
    pdf.add_paragraph(
        "The Air Conditioning Pack converts hot, high-pressure pneumatic bleed air into cold, dry conditioned air for the cabin and flight deck. "
        "Commercial jet transports use an Air Cycle Machine (ACM) operating on the reverse Brayton cycle:"
    )

    acm_table = [
        ["Pack Flow Control Valve", "Regulates incoming pneumatic bleed mass flow into the pack.", "Modulates mass flow based on passenger load and cooling demand."],
        ["Primary Heat Exchanger", "Hot bleed air is cooled by external ambient RAM AIR in ram air duct.", "Air temperature drops significantly while pressure remains high."],
        ["Centrifugal Compressor", "ACM compressor compresses the air again, increasing its pressure and temperature.", "Prepares air for maximum energy extraction across turbine."],
        ["Secondary Heat Exchanger", "Further cools high-pressure air using external ram air.", "Removes compression heat before air enters the expansion turbine."],
        ["Expansion Turbine", "High-pressure air expands rapidly across turbine blades to drive the compressor and ram air cooling fan.", "ULTRA-COLD AIR GENERATION: Air temperature drops precipitously (down to -10°C to +2°C) as internal heat energy is converted into mechanical work to spin the shaft!"],
        ["Water Separator", "Removes condensed moisture via swirling centrifugal coalescer bag.", "Prevents fog, snow, or ice pellets from entering passenger cabin distribution ducts."]
    ]
    pdf.add_table(["Component", "Thermodynamic Function & Process", "Airflow & Temperature State"], acm_table, col_widths=[130.0, 200.0, 170.0])

    pdf.add_callout(
        "trap",
        "ACM Boot-Strap Cycle (Compounding Work)",
        "- The compressor and turbine of the Air Cycle Machine are mounted on a COMMON SHAFT.\n"
        "- The turbine extracts heat energy from the air to spin the shaft. That shaft power directly DRIVES THE PACK COMPRESSOR and the ram air cooling fan!\n"
        "- This self-sustaining thermodynamic loop is known as the 'bootstrap cycle'.",
        max_chars=86
    )

    pdf.add_heading_1("3. Cabin Temperature Control & Trim Air System")
    pdf.add_paragraph(
        "Modern commercial aircraft divide the fuselage into distinct temperature zones (Flight Deck, Forward Cabin, Aft Cabin):"
    )
    pdf.add_bullet("Cold Base Supply", "The air conditioning packs output conditioned air at a cold baseline temperature corresponding to the zone demanding the most cooling.")
    pdf.add_bullet("Trim Air Valves", "Uncooled, hot bleed air from upstream of the packs ('trim air') is piped to individual distribution ducts. Modulating trim air valves mix hot air with cold pack air to satisfy specific zone thermostat demands.")
    pdf.add_bullet("Cabin Air Recirculation", "High-efficiency particulate air (HEPA) fans recirculate approximately 50% of cabin air, blending it with 50% fresh outside pack air. This reduces engine bleed air consumption, saving significant fuel while maintaining optimal ventilation rates.")

    pdf.add_heading_1("4. AviationExam Practice Questions (with Explanations)")
    questions_ch05 = [
        ("Q1: In an Air Cycle Machine (ACM) air conditioning pack, what thermodynamic component produces the dramatic temperature drop?",
         "[A] The primary heat exchanger\n[B] The expansion turbine, where air expands and does mechanical work spinning the shaft\n[C] The centrifugal compressor\n[D] The water separator",
         "CORRECT: [B]. The expansion turbine forces the air to perform work (spinning the compressor and fan). The energy consumed to perform work comes directly from the heat energy of the air, causing its temperature to plummet below 0°C."),
        ("Q2: What is the primary operational function of the 'trim air' system in a modern commercial airliner?",
         "[A] To vent excess cabin pressure overboard\n[B] To add hot engine bleed air to cold pack air in individual duct zones to achieve selected cabin temperatures\n[C] To heat the engine cowl\n[D] To de-ice the wing leading edge",
         "CORRECT: [B]. The packs deliver cold air sized for the zone needing the most cooling. Individual zone trim air valves inject hot bleed air to modulate the temperature in each zone independently."),
        ("Q3: Why is engine bleed air cooled in an engine pylon precooler before entering the pneumatic distribution manifold?",
         "[A] To prevent cabin air from smelling like jet fuel\n[B] To reduce raw bleed air temperature (which can reach 400°C) down to ~200°C to protect aluminum ducting and valves\n[C] To condense water out of the air\n[D] To increase engine fuel efficiency",
         "CORRECT: [B]. Raw compressor bleed air is dangerously hot (up to 400°C). The precooler uses engine fan bypass air to bring it down to ~200°C, ensuring ducting and valves are not damaged.")
    ]

    for q_text, opts, exp in questions_ch05:
        pdf.add_heading_2(q_text)
        pdf.add_paragraph(opts, max_chars=88)
        pdf.add_callout("definition", "Detailed Answer Explanation", exp, max_chars=86)

    pdf.compile_pdf(pdf_path)
    print(f"AGK Chapter 5 compiled: {pdf_path}")


def build_agk_ch06():
    pdf_path = os.path.join(OUTPUT_DIR, "021_ch06_pressurisation_systems.pdf")
    pdf = PDFBuilder("Airframe & Systems", "021", "Chapter 6: Pressurisation Systems")

    # Cover / Header Banner
    pdf.add_title_banner(
        "Airframe & Systems",
        6,
        "Pressurisation Systems (Regimes & Outflow Valves)",
        "217-234"
    )

    pdf.add_heading_1("1. Pressurization Principles & Differential Pressure Limits")
    pdf.add_paragraph(
        "Passenger transport aircraft fly in the thin upper atmosphere (FL 300 to FL 430) for engine fuel efficiency and to avoid adverse weather. "
        "The cabin must be pressurized to maintain physiological oxygen saturation without requiring oxygen masks:"
    )
    pdf.add_bullet("Cabin Altitude", "The equivalent altitude inside the passenger cabin corresponding to the internal pressure. Under CS-25/FAR-25, normal maximum cabin altitude is 8,000 ft (ambient pressure ~750 hPa). Modern airliners (A350, B787) maintain 6,000 ft cabin altitude due to composite fuselage strength.")
    pdf.add_bullet("Differential Pressure (Delta-P)", "The difference between internal cabin pressure (P_int) and external atmospheric ambient pressure (P_amb): Delta-P = P_int - P_amb. Maximum design differential pressure is typically 8.0 to 9.0 psi (aluminum airframes) and up to 9.4 psi (composite airframes).")
    pdf.add_bullet("Cabin Rate of Climb / Descent", "Rate of change of cabin pressure expressed in feet per minute. Normal passenger comfort limits: +500 ft/min during climb; -300 ft/min during descent.")

    pdf.add_heading_1("2. Outflow Valve & Pressure Regulation Architecture")
    pdf.add_paragraph(
        "A common misconception is that pressurization is controlled by varying incoming air supply. "
        "In reality, incoming air conditioning pack mass flow is CONSTANT; cabin pressure is regulated entirely by controlling the EXHAUST RATE of air overboard:"
    )

    press_components = [
        ["Outflow Valve (OFV)", "Lower rear fuselage (under pressure bulkhead).", "Modulates exhaust area from fully open (ground) to nearly closed (cruise). Controlled by dual digital pressurization controllers."],
        ["Positive Relief Valves", "Fuselage pressure shell.", "Spring-loaded mechanical safety valves. Open automatically if cabin differential pressure exceeds maximum structural limit (e.g. 8.6 to 9.1 psi) to PREVENT FUSELAGE EXPLOSION!"],
        ["Negative Relief Valves (Inward)", "Fuselage pressure shell.", "Inward-opening spring valves. Open if ambient pressure exceeds cabin pressure (e.g. in rapid emergency dive), preventing fuselage structural crushing (max negative diff ~ -0.5 psi)."],
        ["Dump Valve (Safety Valve)", "Electrically or pneumatically signaled.", "Dumps all cabin pressure to ambient when aircraft touches down on runway or when pilot selects DUMP switch."]
    ]
    pdf.add_table(["Valve / Unit", "Engineering Location", "Operational Function & Pressure Limit"], press_components, col_widths=[125.0, 155.0, 220.0])

    pdf.add_callout(
        "trap",
        "Cabin Altitude Warning & Passenger Oxygen Trigger Points",
        "- 8,000 ft: Normal maximum cabin altitude in commercial cruise.\n"
        "- 10,000 ft: CABIN ALTITUDE WARNING! Audio horn / master warning light triggers. Flight crew must immediately don oxygen masks (100% oxygen) and initiate emergency descent if uncontrollable!\n"
        "- 14,000 ft: AUTOMATIC PASSENGER OXYGEN MASK DEPLOYMENT. Chemical generator masks drop automatically from overhead passenger service units (PSU).",
        max_chars=86
    )

    pdf.add_heading_1("3. Decompression Categories & Physiological Risks")
    pdf.add_paragraph(
        "Loss of cabin pressurization can occur through seal failure, door release, or structural breach:"
    )
    pdf.add_bullet("Slow / Gradual Decompression", "Loss of pressure takes longer than 10 seconds. Extremely insidious: flight crew may succumb to hypoxia without recognizing symptoms unless instrument warnings are monitored.")
    pdf.add_bullet("Rapid Decompression", "Loss of pressure occurs between 1 and 10 seconds. Accompanied by loud bang, rush of air toward breach, sudden fogging (moisture condensation as temperature drops), and drop in cabin temperature.")
    pdf.add_bullet("Explosive Decompression", "Loss of pressure occurs in LESS THAN 0.5 SECONDS (faster than lungs can decompress without damage). Lungs suffer trauma if pilot holds breath; Time of Useful Consciousness (TUC) is slashed by 33% to 50%!")

    pdf.add_heading_1("4. AviationExam Practice Questions (with Explanations)")
    questions_ch06 = [
        ("Q1: How is cabin pressure regulated in a modern jet transport aircraft during normal flight?",
         "[A] By varying the engine bleed air mass flow rate entering through the packs\n[B] By modulating the position of the outflow valve(s) to control the rate of air escaping overboard\n[C] By opening and closing cabin passenger doors\n[D] By throttling the engine fuel pumps",
         "CORRECT: [B]. The air conditioning packs deliver a constant mass flow of fresh air. The digital pressurization controller commands the outflow valve to open or close, regulating the rate of air exhausted overboard."),
        ("Q2: At what cabin pressure altitude does the master cabin altitude warning horn activate under commercial transport regulations?",
         "[A] 8,000 ft\n[B] 10,000 ft\n[C] 14,000 ft\n[D] 18,000 ft",
         "CORRECT: [B]. At 10,000 ft cabin altitude, an intermittent audio horn and visual warning alert the pilots to don oxygen masks immediately. (Passenger masks deploy automatically at 14,000 ft)."),
        ("Q3: What is the primary operational purpose of inward-opening negative relief valves on a pressurized aircraft fuselage?",
         "[A] To prevent cabin overpressure in cruise\n[B] To prevent external atmospheric ambient pressure from exceeding internal cabin pressure, which would crush the fuselage inward\n[C] To allow passenger cabin smoke evacuation\n[D] To supply ram air to the engines",
         "CORRECT: [B]. Aircraft fuselage structures are designed as pressure vessels to withstand internal pressure (tension). They have poor resistance to external pressure (compression/crushing). Negative relief valves open inwards to equalize pressure if ambient exceeds cabin pressure."),
        ("Q4: Why does explosive decompression reduce the Time of Useful Consciousness (TUC) by 33% to 50% compared to gradual decompression at the same altitude?",
         "[A] The blood freezes instantly\n[B] Ambient pressure drops faster than alveolar partial pressure, causing reverse diffusion of oxygen from the blood into the lungs\n[C] Adrenaline blocks hemoglobin\n[D] Heart rate drops to zero",
         "CORRECT: [B]. In explosive decompression, alveolar oxygen pressure drops instantly below blood capillary oxygen pressure. Oxygen diffuses backwards out of the venous blood into the lungs, draining oxygen from the brain rapidly.")
    ]

    for q_text, opts, exp in questions_ch06:
        pdf.add_heading_2(q_text)
        pdf.add_paragraph(opts, max_chars=88)
        pdf.add_callout("definition", "Detailed Answer Explanation", exp, max_chars=86)

    pdf.compile_pdf(pdf_path)
    print(f"AGK Chapter 6 compiled: {pdf_path}")


if __name__ == "__main__":
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    build_agk_ch04()
    build_agk_ch05()
    build_agk_ch06()
